### ISSUE TITLE
Not building successfully using KLH10

### ISSUE THREAD

**Issue by b4** [PDP-10/its#402] opened 2017-01-08 20:42 UTC
:PDUMP DSK:.MAIL.;COMSAT LAUNCH
*:kill
*:job comsat
!
*:load .mail.;comsat launch
*debug/'NEW$:   0   -1
mfinit$g
.VAL 0; DEATHV+2>>JRST DEATHV+1
/
:kill
invalid command name "abort"
    while executing
"abort"
    invoked from within
"expect -exact $w"
    (procedure "respond" line 2)
    invoked from within
"respond "*" ":kill\r""
    (procedure "initialize_comsat" line 6)
    invoked from within
"initialize_comsat"
    (file "../build.tcl" line 606)
    invoked from within
"source ../build.tcl"
    (file "build/klh10/build.tcl" line 54)

SIMH does not bomb here

**Comment by larsbrinkhoff** [comment] 2017-01-08 20:51
The build went fine in Travis CI:  
https://travis-ci.org/PDP-10/its/jobs/190050150#L3923

Running COMSAT RFINIT needs networking, so I'm guessing there is a problem in that area.  I don't know if it's a problem with KLH10 configuration, or your host system.

SIMH skips this part, because we don't support networking with that emulator.

**Comment by larsbrinkhoff** [comment] 2017-01-08 20:54
Both Eric and I use Linux to run the emulators.  I don't know how well KLH10 supports FreeBSD.

**Comment by eswenson1** [comment] 2017-01-08 20:57
This does not bomb for me under KLH10 under Ubuntu Linux.  It seems COMSAT isn't initializing properly in your environment.

**Comment by b4** [comment] 2017-01-08 21:05
I'm running on ubuntu here - i'll investigate networking and see what's going on.

**Comment by b4** [comment] 2017-01-08 21:19
Trying 10.12.3.10...
Connected to 10.12.3.10.
Escape character is '^]'.
DB-ITS

DB ITS.1647. DDT.1546.
TTY 11
2. Lusers, Fair Share = 98%

ITS is up - but still bombing on COMSAT init

.VAL 0; DEATHV+2>>JRST DEATHV+1
 LOGIN  11TLNT 0 005001 13:16:41
 LOGOUT ___006 11 13:17:02
 LOGIN  11TLNT 0 005001 13:17:02
invalid command name "abort"
    while executing
"abort"
    invoked from within

**Comment by eswenson1** [comment] 2017-01-08 21:25
Did you make sure to update all the places where the IP address must be set correctly?  It is best to try this where the ip address of the machine is 192.168.1.100 (or whatever I have the IP address set to). Otherwise, you have to patch/update a bunch of places.

My guess is that while you've told KLH10 where machine is (in the INI file), ITS thinks it is at a different place.  They all have to match.

**Comment by b4** [comment] 2017-01-08 21:33
Bah!  I missed SYSHST; H3TEXT

**Comment by larsbrinkhoff** [comment] 2017-01-10 20:21
So, can we close this?

**Comment by b4** [comment] 2017-01-10 20:22
Sorry - fixed networking and it still failed.

**Comment by eswenson1** [comment] 2017-01-10 20:24
Any way you can use the default, configured ip address first to make sure that works?  Then, we can try to track down where you haven't updated the ip address correctly?  -- Eric

**Comment by b4** [comment] 2017-01-18 01:57
Sorry for the delay - was away from a computer after work on Thursday-Monday morning and was busy yesterday.

Can do!

**Comment by b4** [comment] 2017-01-18 02:31
Trying to use the default configured IP results in networking not coming up at all - it seems to never start the dpimp process - and print no error.

Looking at the config...
DEFOPT IMPUS3==<IPADDR 192,168,1,100>  	; IP address
DEFOPT NM%IMP==<IPADDR 255,255,255,248>	; Subnet mask

and the gateway is 192.168.0.45...how did this work?

**Comment by b4** [comment] 2017-01-18 02:35
Okay - with it up using the pre-configured IP everything works correctly.

**Comment by b4** [comment] 2017-01-18 03:21
It took me far too long to realise the address stuff is classful and that 10.12/16 is a different class than the previously configured stuff...

Now to look at what comsat is actually expecting

**Comment by larsbrinkhoff** [comment] 2017-01-26 10:43
I'm trying to simplify the networking configuration by putting all parameters in the Makefile.

However, I may be seeing the same problem as @b4.  Indeed even just chaning the IP number sligthly to 192.168.1.101 triggers the COMSAT valret.

**Comment by larsbrinkhoff** [comment] 2017-01-26 12:12
Oh, COMSAT's BUGHST isn't that important.  It probably isn't the cause of the build failure, because it doesn't matter if it's set to 192.168.1.100 or 192.168.1.101.  As long as the other places are 192.168.1.100, that is.

**Comment by eswenson1** [comment] 2017-01-26 21:45
So you're saying that if you change ALL the relevant places from 192.168.1.101, including COMSAT's, that COMSAT fails to initialize?  I've successfully booted an ITS system on two distinct IP addresses before (ES-ITS), so are you sure you aren't just leaving one place unpatched/unchanged?

**Comment by b4** [comment] 2017-01-27 01:06
I believe I am also incorrectly entering the addresses.

**Comment by larsbrinkhoff** [comment] 2017-01-27 05:48
@eswenson1 Yes, that's what I'm saying.  I certainly *believe* I have changed all places, as documented in README.md.

But it's probably just a stupid mistake somewhere.  If you have time, could you make a new system with a different IP number, and post the diff?

**Comment by larsbrinkhoff** [comment] 2017-02-13 13:08
I think I know what the problem is.

The binary file SYSBIN; HOSTS3 BIN contains the host table with the old IP number.  It should be regenerated by calling H3MAKE from build.tcl, but from what I can see, it isn't.

I tried to run H3MAKE myself, but it doesn't seem to work.  Maybe it thinks the binary is newer than the source or something.

I have now solved it by running SYSHST; HOSTS3 BIN instead.  I'm not sure if that's the right thing to do, though.

**Comment by larsbrinkhoff** [comment] 2017-02-17 06:02
I'm hovering my mouse pointer over the "Close" button...

**Comment by b4** [comment] 2017-02-17 06:03
Proceed.

**Comment by larsbrinkhoff** [comment] 2017-02-17 06:04
Done!

**Closed by larsbrinkhoff** 2017-02-17 06:04 UTC
Labels: bug, host
