### ISSUE TITLE
When trying to start simh-based image, "its" command responds with "DIRNF"

### ISSUE THREAD

**Issue by jeffhhk** [PDP-10/its#2113] opened 2022-04-11 22:03 UTC
I encountered the same bug reproduction as the reporter of #2099 did, on a different platform.

Platform: Ubuntu 20.04 LTS
Compiler: gcc 9.4.0
Branch: master
Commit: 780e40c 2022-04-07 "Updated MGPRIM as per RRS to fix CORD function."

```
make EMULATOR=simh
./start
```
At the prompt , typing "its" to start the system responds with "DIRNF".  Grepping the code "DIRNF" seems to be something to the extent that a directory was not found.  Looks like this:
```
    ./start
        This start script takes several command line arguments:

        help - Display this help text.
        gt40 - Start a GT40 emulator.
        vt52 - Start a VT52 emulator.


        PDP-10 simulator V4.0-0 Current        git commit id: e1db7dec
        out/simh/boot-6> at dz0 10004
        Listening on port 10004
        out/simh/boot-8> at dz0 line=7,10018
        Line 7 Listening on port 10018
        out/simh/boot-10> at tty line=6,10019
        Non-existent device

         DSKDMP
        its
         DIRNF
```
As a newbie I don't see any obvious way to circumvent the DIRNF error based on this image.

On the other hand, based on the comments on #2099, I can confirm that I can circumvent the DIRNF failure by rolling back 87 commits from the current HEAD 780e40c:

```
    git checkout 36be2f7^
    git submodule update --recursive
    git clean -f -d -x
    make EMULATOR=simh
```
Following this I am able to complete the startup procedure at https://github.com/PDP-10/its#usage :

terminal 1:
```
its
ESC-G
```

terminal 2:
```
telnet localhost 10004
C-z
```

By contrast, checking out the HEAD of master and reverting commit 36be2f7 does not succeed in building a working image.

**Comment by larsbrinkhoff** [comment] 2022-04-12 05:45
Thanks.  This seems to be exactly the same as #2099.  The problem *ought* to be easy to fix, but it has eluded me for quite some time.

Workarounds are avilable:
- Use one of the other emulators.
- Use a older commit, as you did.
- Do not boot the on-disk copy of DSKDMP, but from a tape instead.

**Comment by larsbrinkhoff** [comment] 2023-01-12 17:43
Closing as duplicate of #2099.

**Closed by larsbrinkhoff** 2023-01-12 17:43 UTC
Labels: duplicate
