### ISSUE TITLE
CTENSR and EIGEN fasl files

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1125] opened 2018-08-01 12:44 UTC
Hello,

I'm trying to locate the fasl file of CTENSR and EIGEN.
In the build script, those file should be compiled:

```
### build ctensr for macsyma
respond "*" "macsym\013"
respond "(C1)" "compile_lisp_file(translate_file(\"sharem\\;packg >\")\[2\]);"
respond "(C2)" "compile_lisp_file(translate_file(\"tensor\\;ctensr funcs\")\[2\]);"
respond "(C3)" "quit();"

### build eigen for macsyma
respond "*" "macsym\013"
respond "(C1)" "compile_lisp_file(translate_file(\"share\\;eigen >\")\[2\]);"
respond "Type ALL;" "all;"
respond "(C2)" "quit();"
```
but I cannot find them either in SHARE, SHARE2, SHAREM or TENSOR directory.

Am I missing something ?

thanks,
Fausto

**Comment by eswenson1** [comment] 2018-08-01 13:51
I'm not sure I understand your question. The source files for CTENSR and EIGEN are in source tree and are first translated to LISP (the sources are written in Macsyma) and then the LISP files are compiled to FASL files.  The compile_lisp_file() Macyma function invokes the lisp compiler to compile the LISP to FASL.  The translate_file() Macyma function translates the Macsyma code in the source file to LISP code.  The source for CTENSR is TENSOR; CTENSR FUNCS.  The source for EIGEN is SHARE; EIGEN 8.

**Comment by eswenson1** [comment] 2018-08-01 13:53
Oh, I guess I do understand what you're asking.  If the above process is actually working, then wouldn't there be FASL files as byproducts of those operations. There should be.  I just booted DB and don't see them. They used to be there. I wonder whether the build process has broken the ability of compile_lisp_file and translate_file again.  Probably best to run a build and watch what happens when those commands are executed. They must be giving errors not caught by the build script.

**Comment by eswenson1** [comment] 2018-08-01 13:55
And by the way, this used to work and did when I first merged this code in. I saw the FASL files being created -- so something must have broken since that time. I had this working in two different ways: 1) compile_lisp_file and translate_file, 2) translate_file only, and then a breakout to a standalone lisp compiler.  We switched back to 2) after 1) broke the SIMS build, then, we fixed whatever the cause was, and switched back to 1).

**Comment by atsampson** [comment] 2018-08-01 14:02
There are indeed a couple of errors that the build script doesn't catch...

```
(C1) compile_lisp_file(translate_file("sharem\;packg >")[2]);
[...]
Translation begun on DSK:SHAREM;PACKG 7.
NOT FILE: ((DSK SHAREM) PACKG TRLISP)

(C2) compile_lisp_file(translate_file("tensor\;ctensr funcs")[2]);

Translation begun on DSK:TENSOR;CTENSR FUNCS.
[...]

(C1) compile_lisp_file(translate_file("share\;eigen >")[2]);
[...]
NOT FILE: ((DSK SHARE) EIGEN TRLISP)
```

\> matching the wrong file?

**Comment by eswenson1** [comment] 2018-08-01 14:11
This used to work before we switched back and forth between methods. I’ll have to debug to see what’s going wrong.

**Comment by eswenson1** [comment] 2018-08-02 19:41
Not that I didn't suspect this, but I did a "git bisect" and learned that this commit -- a08865ce759cfe9d7e22077998476e10f7067ff8 -- is what broke the building of CTENSR and EIGEN (both written in Maclisp and needing translation).  I will investigate further.

**Comment by TheFausap** [comment] 2018-11-03 09:29
Hello, maybe I'm missing something, I'm did a git pull 10 mins ago, and CTENSR FASL is not in SHARE directory anymore (EIGEN is present). I found it in TENSOR directory, but in this case tsetup() doesn't work.
Also, is it possible to compile also ITENSR (always in the TENSOR directory) ?

**Comment by eswenson1** [comment] 2018-11-03 15:01
If I remember correctly, the build builds CTENSR FASL from source. Check macsyma.tcl. If you don’t end up with a FASL, the build got broken somehow.

**Comment by larsbrinkhoff** [comment] 2018-11-03 15:42
There is a TENSOR; CTENSR FUNCS which is built to a FASL.  So maybe there should be a link from SHARE?

**Comment by eswenson1** [comment] 2018-11-03 15:46
Where is the build currently putting the FASL? This used to work and I don’t remember changing it.

**Comment by larsbrinkhoff** [comment] 2018-11-03 15:48
In TENSOR, like so:

```
respond "(C2)" "compile_lisp_file(translate_file(\"tensor\\;ctensr funcs\")\[2\]);"

**Comment by eswenson1** [comment] 2018-11-03 16:06
Interesting. I wonder why I didn’t have either a link or an output file spec so that it would end up in SHARE? I wonder if this got lost when we transitioned from compiling from lisp to macsyma to lisp to macsyma. I’ll look and fix.

**Comment by eswenson1** [comment] 2018-11-03 16:07
By the way the MIT-MULTICS backup tape set appears to include a Macsyma tape. Wonder what that will yield?

**Closed** 2018-11-04 13:48 UTC
Labels: question
